# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en"
title                    : "Friends, Peace, & Sanctuary"
title_separator          : "-"
name                     : "Swarthmore College"
# url                      : # "https://mmistakes.github.io"
url                      : #""
baseurl                  : "/fps.swarthmore.edu"
languages                : ["en", "ar"]
exclude_from_localizations: ["assets","assets/js","assets/images","assets/css","assets/fonts"]

# Social Sharing
twitter:
  username               : "fpsbookarts"
facebook:
  username               : "fpsbookarts"
  app_id                 :
  publisher              :
instagram:
  username               : "fpsbookarts"

# Analytics
analytics:
  provider               : custom # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-58250963-5


# Site Author
author:
  name             : "Swarthmore College Libraries"
  facebook         :
  instagram        :
  twitter          :
  url              : "https://www.swarthmore.edu/libraries"

# Prose settings
prose:
  rooturl: '_posts'
  media: 'assets/images'

# Placeholders
placeholder:
  image: logo-placeholder.svg
  bio: >
    As part of FPS, members of the Iraq and Syrian refugee communities of Philadelphia have graciously contributed their valuable time, input and lent their experiences to the project.


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: nested # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-minimagick
  - jemoji
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# mini magick image processing
mini_magick:
  resize:
    source: assets/images
    destination: assets/images
    resize: "800x>"

jekyll-archives:
  enabled: ['tags','categories']
  layout: archive-taxonomy
  permalinks:
    tag: '/:name/'
    category: '/:name/'

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
